name: Release workflow for tagged versions
on:
  release:
    types:
      - created

jobs:
  generic:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Add LICENSE and README.md
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            README.md

  postgres:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # skipping 12, no tag for
        osrelease:
          - rockylinux8
          - rockylinux9
          - fedora38
          - fedora39
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build rpms'
        run: |
          docker-compose run pgbuilder
        env:
          PGGITTAG: ${{ github.ref }}
          IMAGETAG: ${{ matrix.osrelease }}

      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            oriolepg/rpms/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build oriolepg image'
        run: |
          docker build . --build-arg="IMAGETAG=${{ matrix.osrelease }}" --tag oriolepg
          docker tag oriolepg "ghcr.io/oriole-rpms/oriolepg:${{ github.ref_name }}-${{ matrix.osrelease }}"

      - name: 'Push to ghcr.io'
        run: docker push -a ghcr.io/oriole-rpms/oriolepg
